defaults:
  resources:
    instance-type: P6000

jobs:
  dummy-job:
    uses: script@v1
    with:
      script: |-
        echo "Inputs: "
        ls -la /inputs/data
      image: nvcr.io/nvidia/pytorch:21.02-py3
    inputs:
      data:
        type: dataset
        with:
          ref: blindbot-data
    outputs:
      models:
        type: dataset
        with:
          ref: blindbot-models